# -*- coding: utf-8 -*-
"""Project_1_India_Ehrhardt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCdOiQbsOxUun6LbycXGIRZybZP4mJSF
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.metrics import mean_squared_error as MSE
from sklearn.tree import DecisionTreeRegressor

myData = pd.read_csv('Mushroom_data.csv')
myData.head(10)

myData = myData.fillna('missing')
myData_encoded = pd.get_dummies(myData)
myData_encoded.head(10)

#Split data into training and testing

X = myData_encoded.drop(['class_p', 'class_e'], axis = 1)
y = myData_encoded['class_p']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=5, stratify=y)

# Model 1 - Decision Tree
clf = DecisionTreeClassifier(max_depth = 100, min_samples_split = 2, random_state = 5)
clf.fit(X_train, y_train)

#Visualization of Model 1 - Decision Tree
fig = plt.figure(figsize=(20,25))
tree.plot_tree(clf, filled = True, feature_names= X_train.columns, class_names = ['poisonous', 'edible']);

#Model 1 accuracy score

testPredictions = clf.predict(X_test)
accuracy1 = accuracy_score(y_test, testPredictions)
print("Decision Tree Accuracy:", accuracy1)
print("Confusion Matrix")
print(confusion_matrix(y_test, testPredictions))

#Model 2 - Random Forest

rf = RandomForestClassifier(n_estimators = 100, min_samples_split = 2, random_state=5)

rf.fit(X_train, y_train)

#Model 2 accuracy score

rfPredictions = rf.predict(X_test)
accuracy2 = accuracy_score(y_test, rfPredictions)
print("Random Forest Accuracy:", accuracy2)
print("Confusion Matrix")
print(confusion_matrix(y_test, rfPredictions))